/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiPlacePhotoRouteImport } from './routes/api/place-photo'
import { Route as LocalPlaceIdRouteImport } from './routes/local.$placeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacePhotoRoute = ApiPlacePhotoRouteImport.update({
  id: '/api/place-photo',
  path: '/api/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalPlaceIdRoute = LocalPlaceIdRouteImport.update({
  id: '/local/$placeId',
  path: '/local/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/local/$placeId': typeof LocalPlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/local/$placeId': typeof LocalPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/local/$placeId': typeof LocalPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/privacidade'
    | '/termos'
    | '/api/place-photo'
    | '/local/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/privacidade'
    | '/termos'
    | '/api/place-photo'
    | '/local/$placeId'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/privacidade'
    | '/termos'
    | '/api/place-photo'
    | '/local/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  DoarRoute: typeof DoarRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPlacePhotoRoute: typeof ApiPlacePhotoRoute
  LocalPlaceIdRoute: typeof LocalPlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-photo': {
      id: '/api/place-photo'
      path: '/api/place-photo'
      fullPath: '/api/place-photo'
      preLoaderRoute: typeof ApiPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$placeId': {
      id: '/local/$placeId'
      path: '/local/$placeId'
      fullPath: '/local/$placeId'
      preLoaderRoute: typeof LocalPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  DoarRoute: DoarRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPlacePhotoRoute: ApiPlacePhotoRoute,
  LocalPlaceIdRoute: LocalPlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
